version: '3.3'
services:
  mariadbservice:
    image: mariadbservice:latest
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_USER: user
      MYSQL_ROOT_PASSWORD: password

  bookingservice:
    image: bookingservice
    restart: always
    ports:
      - 8080:8080
    links:
      - mariadb

  carservice:
    image: carservice
    restart: always
    ports:
      - 8081:8081
    links:
      - mariadb

  userservice:
    image: userservice
    restart: always
    ports:
      - 8084:8084
    links:
      - mariadb