version: '3.3'
services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: carpooldb
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPassword

  mariadbservice:
    image: mariadbservice
    build: .
    restart: always
    ports:
       - "8006:8006"
    depends_on:
       - mariadb
    environment:
      MYSQL_DATABASE: carpooldb
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPassword
      HOST: mariadb

  bookingservice:
    image: bookingservice
    build: .
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mariadbservice
    environment:
      MARIADBSERVICE_HOST: mariadbservice

  carservice:
    image: carservice
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mariadbservice
    environment:
      MARIADBSERVICE_HOST: mariadbservice

  userservice:
    image: userservice
    build: .
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - mariadbservice
    environment:
      MARIADBSERVICE_HOST: mariadbservice