name: build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  # Also trigger on page_build, as well as release created events
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
