name: build
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  # Also trigger on page_build, as well as release created events
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
              java-version: '11'
              distribution: 'adopt'
          - name: Build Jar
            run: mvn clean install -DskipTests
