name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Get Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Jar file
        run: mvn clean install -DskipTests

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push userservice
        uses: docker/build-push-action@v2
        with:
          context: ./userservice
          push: true
          tags: sanajava/userservice:${{ github.run_number }}

      - name: Build and Push carpoolservice
        uses: docker/build-push-action@v2
        with:
          context: ./carpoolservice
          push: true
          tags: sanajava/carpoolservice:${{ github.run_number }}

      - name: Build and Push bookingservice
        uses: docker/build-push-action@v2
        with:
          context: ./bookingservice
          push: true
          tags: sanajava/bookingservice:${{ github.run_number }}

      - name: Build and Push mariadbservice
        uses: docker/build-push-action@v2
        with:
          context: ./mariadbservice
          push: true
          tags: sanajava/mariadbservice:${{ github.run_number }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar

